apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-model-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churn-model
  template:
    metadata:
      labels:
        app: churn-model
    spec:
      containers:
        - name: churn-model
          image: kodenko/churn_model:latest
          ports:
            - containerPort: 5000
