apiVersion: v1
kind: Service
metadata:
  name: churn-model-service
spec:
  type: NodePort
  selector:
    app: churn-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007  # You can change this if needed
