name: CI/CD - Build & Push Docker Image

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]  # Push to Docker Hub only on merges to main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/churn_model:pr-${{ github.event.pull_request.number || 'manual' }} .

      - name: Push Docker image to Docker Hub
        if: github.event_name == 'push'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/churn_model:pr-${{ github.event.pull_request.number || 'manual' }} ${{ secrets.DOCKER_USERNAME }}/catnip:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/churn_model:latest
